spring.output.ansi.enabled: always
server.port: 10001
security.basic.enabled: false
spring.thymeleaf.cache: false

aws:
  host: http://localhost:8000
  region: us-west-2
  accessKey: "test"
  secretKey: "test"
