db:
  common:
    url: jdbc:mysql://kjarvis.asuscomm.com:13306/jpa_common?useLocalSessionState=true&characterEncoding=UTF-8&useSSL=false
    username: example
    password: example^123
    driverClassName: com.mysql.jdbc.Driver
  shardCount: 1
  shard:
    - url: jdbc:mysql://kjarvis.asuscomm.com:13306/jpa_user0?useLocalSessionState=true&characterEncoding=UTF-8&useSSL=false
      username: example
      password: example^123
      driverClassName: com.mysql.jdbc.Driver

